# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            yoshixi.web
tagline:          'Portfolio'
description:      'Hi this is my repository where i post writups about personal projects, competitions, and blog posts'
url:              https://digitalyoshixi.github.io
baseurl:          '/'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

plugins:
  - jekyll-feed
  - jekyll-gist
